#!/bin/bash

source $HOME/.bashrc
sxhkd -c $HOME/.config/berry/sxhkdrc &

xrdb -merge $HOME/dots/xfiles/Xresources

setxkbmap -layout us -option caps:ctrl_modifier
xcape -e 'Caps_Lock=Escape'


(urxvt &)

# set the bg
hsetroot -add '#2c3539' -add '#b89ca8' -gradient 130

# start bars
tint2 -c $HOME/dots/tint2/time &
tint2 -c $HOME/dots/tint2/desktop &

berryc top_gap 0

berryc border_width 0
berryc inner_border_width 5
berryc title_height 20

berryc focus_color 292d3e
berryc unfocus_color 292d3e
berryc inner_focus_color b89ca8
berryc inner_unfocus_color 343d41
berryc text_focus_color 2c3539
berryc text_unfocus_color 565679
