#!/bin/bash

source $HOME/.bashrc
source $HOME/dots/scripts/colorize
sxhkd -c $HOME/.config/berry/sxhkdrc &

xrdb -merge $HOME/.Xresources

setxkbmap -layout us -option caps:ctrl_modifier
xcape -e 'Caps_Lock=Escape'


(urxvt &)

# set the bg
# hsetroot -add '#2c3539' -add '#b89ca8' -gradient 130
hsetroot -center $HOME/walls/floating_cliffs.png

# start bars
bar

berryc top_gap 0

berryc border_width 0
berryc inner_border_width 5
berryc title_height 20

berryc inner_unfocus_color $COLOR6
berryc text_unfocus_color $COLOR0
berryc inner_focus_color $COLOR8
berryc text_focus_color $COLOR4
