#! /bin/sh
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# set colors
# keep normal color
bspc config normal_border_color $(pallet -x com)
bspc config active_border_color $(pallet -x com)

# active color
bspc config focused_border_color $(pallet -x sec)

# comment color? or maybe block
bspc config presel_feedback_color $(pallet -x block)
