#!/bin/bash
source $HOME/.bashrc
source $HOME/dots/scripts/colorize

setxkbmap -layout us -option caps:ctrl_modifier
xcape -e 'Caps_Lock=Escape'
xrdb -merge $HOME/.Xresources

#urxvt &


#exec berry -f Dina 16
hsetroot -center $HOME/dots/walls/floating_cliffs.png
sxhkd -c $HOME/dots/helium/sxhkdrc &
exec $HOME/dots/scripts/helium_exe
