#!/bin/bash
setxkbmap -layout us -option caps:ctrl_modifier
xcape -e 'Caps_Lock=Escape'
xrdb -merge $HOME/.Xresources

urxvt &

hsetroot -solid "#689a64"

#sxhkd -c $HOME/dots/helium/sxhkdrc &
#exec $HOME/dots/scripts/helium_exe
#exec openbox
exec openbox
