# common
setxkbmap -layout us -option caps:ctrl_modifier
xcape -e 'Caps_Lock=Escape'
source $HOME/.zshrc
sxhkd -c $HOME/dots/sxhkd/sxhkdrc & 
sxhkd -c $HOME/dots/bspwm/sxhkdrc & 
sakura &
dunst &

{
sleep 1
hsetroot -cover $HOME/pics/walls/currbg &
./$HOME/bin/bar &
}&

pipewire &

exec bspwm -c "$HOME/dots/bspwm/bspwmrc"
