# common
setxkbmap -layout us -option caps:ctrl_modifier
xcape -e 'Caps_Lock=Escape'
source $HOME/.zshrc
dunst &
kitty &

{
sleep 1
hsetroot -cover $HOME/pics/walls/currbg &
# TODO: fix bar
# ./$HOME/bin/bar &
# xrandr --output DP-0 --mode 3440x1440 --rate 100
}&
xset r rate 200 50
# pipewire &
picom --backend glx --vsync &

# exec i3
