# common
setxkbmap -layout us -option caps:ctrl_modifier
xcape -e 'Caps_Lock=Escape'
source $HOME/.zshrc
dunst &
kitty &

{
sleep 1
hsetroot -cover $HOME/pics/walls/currbg &
./$HOME/bin/bar &
}&

pipewire &
picom --backend glx --vsync &

exec i3
