#!/usr/bin/env bash
fonts="CozetteVector:pixelsize=10;1"
#-f -*-dina-medium-r-*-*-10-*-*-*-*-*-*-*
fg_alt="$(clrctl.py -x fg_alt)"
fg="$(clrctl.py -x fg)"
bg="$(clrctl.py -x bg)"
fill="$(clrctl.py -x fill)"
primary="$(clrctl.py -x primary)"
p="10"

time_bat() {
	echo "$(date '+%I:%M') | $(bat)"
}

desk() {
		desknum="$(xprop -root | grep '_NET_CURRENT_DESKTOP(CARDINAL)' | awk -F ' = ' '{print $2}')"
		toprint=""
		for i in {0..5}; do
			if [ "$i" == "$desknum" ]; then
				toprint+="%{B${primary}} %{F${fg}}$((i + 1)) %{F-}%{B-}"
			else
				toprint+=" $((i + 1)) "
			fi
		done

		echo -e "${toprint}"
}

call() {
	while true; do
		echo -ne "%{B${primary}}%{O$p}$(date '+%I:%M')%{O$p}%{B-}\
							%{O$p}$(desk)%{O$p}\
							%{O$p}$(bat)%{O$p}"
		sleep 1
	done
}

pkill lemonbar
call | lemonbar -g 1920x30 ${fonts}  -F ${fg} -B ${bg}
