#!/usr/bin/env bash
fonts="-f -*-dina-medium-r-*-*-10-*-*-*-*-*-*-*"
#colors=" -B "$(clr -x color0)" -F "$(clr -x color3)""
colors=" -F "$(clr -x color2)" -B "$(clr -x color0)""
desk() {
	while true; do
		state="$(xprop -root | grep -i "tag_state" | awk -F ' = ' '{ gsub(/"/, "", $2); print $2 }')"
		nobel=(None He Ne Ar Kr Xe Rn)
		toprint=""
		for i in {1..6}; do
			if [[ "${state:i:1}" == "i" ]]; then
				toprint+="%{F#${COLOR5}}[${nobel[i]}]"
			elif [[ "${state:i:1}" == "a" ]]; then
				toprint+="%{F-}[${nobel[i]}]"
			else
				toprint+="%{F#${COLOR15}}[${nobel[i]}]"
			fi
		done
		echo -e "%{c}${toprint}"
		sleep 0.3
	done
}

time_bat() {
	while true; do
		echo "%{c}$(date '+%I:%M') | $(bat)"
		sleep 1
	done
}

# desk | lemonbar -g 180x25+10+10 ${fonts} ${colors} &
pkill lemonbar
time_bat | lemonbar -g 120x30+900+10 ${colors} &
# time_bat | lemonbar -g 120x30+2820+10 ${colors} &
