#!/usr/bin/env bash
bat0="$(cat /sys/class/power_supply/BAT0/capacity)"
bat1="$(cat /sys/class/power_supply/BAT1/capacity)"
stat0="$(cat /sys/class/power_supply/BAT0/status)"
stat1="$(cat /sys/class/power_supply/BAT1/status)"

if [[ "$stat0" == "Charging" || "$stat1" == "Charging" ]]; then
	echo "%{u$(clr -x color2)}$(((bat0 + bat1) / 2))%"
else 
	echo "$(((bat0 + bat1) / 2))%"
fi
