#!/usr/bin/env bash

desknum="$(xprop -root | grep "_NET_CURRENT_DESKTOP(CARDINAL)" | awk -F ' = ' '{print $2}')"
toprint=""
for i in {0..5}; do
	if [ "$i" == "$desknum" ]; then
		toprint+="%{B$($HOME/dots/scripts/clrmgr -x color8)}%{u$($HOME/dots/scripts/clrmgr -x color2)} $((i + 1)) %{-u}%{B-}"
	else
		toprint+=" $((i + 1)) "
	fi
done

echo -e "${toprint}"
