#!/bin/bash
vars="-i -x 560 -y 405 -w 800 -l 15 \
-nb "$(clrmgr.py -x bg)" -nf "$(clrmgr.py -x fg)" \
-sb "$(clrmgr.py -x secondary)" -sf "$(clrmgr.py -x bg)""

if [[ "$1" == "-m" ]]; then
	dmenu $vars < /dev/stdin
else
	dmenu_run ${vars}
fi

