#!/bin/bash
vars="-i -x 560 -y 405 -w 800 -l 15 \
-nb "$(pallet -x bg)" -nf "$(pallet -x fg)" \
-sb "$(pallet -x secondary)" -sf "$(pallet -x bg)""

if [[ "$1" == "-m" ]]; then
	dmenu $vars < /dev/stdin
else
	dmenu_run ${vars}
fi

