#!/bin/sh
xrandr --output eDP1 --mode 1920x1080 --pos 1920x0 --rotate normal \
--output DP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
sleep 1.5
feh --bg-scale $HOME/dots/walls/forest.jpg
setxkbmap -layout us -option caps:ctrl_modifier
