#!/bin/bash
cc="/home/xenone/dots/scripts/clrmgr"

# lock the screen
i3lock -t -i /home/xenone/dots/walls/tiles/hideout.png \
--composite \
-k \
--insidecolor=00000000 \
--insidewrongcolor=00000000 \
--insidevercolor=00000000 \
--ringcolor="$($cc -n bg)ff" \
--ringvercolor="$($cc -n primary)ff" \
--separatorcolor="$($cc -n bg)ff" \
--ringwrongcolor="$($cc -n alert)ff" \
--linecolor=00000000 \
--keyhlcolor="$($cc -n primary)ff" \
--bshlcolor="$($cc -n bg_alt)ff" \
--noinputtext="" \
--ring-width 30 \
--radius 150 \
--indpos="w/2:h/3 + 100" \
--timepos="w/2:h/2 + 200" \
--timestr="Hello $(whoami), it is %I:%M" \
--datestr="%A, %m %Y"

