#!/bin/bash
set -e

DP1_STATUS=$(</sys/class/drm/card0/card0-DP-1/status )
LAP="eDP-1"
MON="DP-1"

if [ "connected" == "$DP1_STATUS" ]; then
	xrandr --output ${LAP} --scale 1.0 --mode 1920x1080 --pos 1920x0 --rotate normal \
		--output ${MON} --primary --mode 1920x1080 --pos 0x0 --rotate normal
	sleep 0.5
	feh --bg-tile $HOME/dots/walls/tiles/hideout.png
	setxkbmap -layout us -option caps:ctrl_modifier
	#/usr/bin/notify-send -t 5000 "Plugged in"
else
	xrandr --output "${LAP}" --primary --scale 1.0 --mode 1920x1080 --pos 0x0 --output "${MON}" --off
	#/usr/bin/notify-send -t 5000 "unplugged"
fi
