#!/bin/bash
set -e

DP1_STATUS=$(</sys/class/drm/card0/card0-DP-1/status )

if [ "connected" == "$DP1_STATUS" ]; then
	xrandr --output eDP1 --mode 1920x1080 --pos 1920x0 --rotate normal \
	--output DP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
	sleep 0.5
	feh --bg-scale $HOME/dots/walls/forest.jpg
	setxkbmap -layout us -option caps:ctrl_modifier
	/usr/bin/notify-send -t 5000 "Plugged in"
else
	xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --output DP1 --off
	/usr/bin/notify-send -t 5000 "unplugged"
fi
