#!/usr/bin/env bash
xrdb -query | awk '
	$1 ~ "*.color" {
		gsub(/^\*\./, "", $1)
		gsub(/:$/, "=", $1)
		gsub(/#/, "", $2)
		print toupper($1) "\"" $2 "\""
	}
' > $HOME/dots/scripts/colorize
source colorize
