# prompt
#PS1='%B%F{10}%~%b :(
PS1='%B%F{10}%~%b 🌱
$%F{reset} '

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GO111MODULE=on

# vterm printf
vterm_printf(){
    if [ -n "$TMUX" ]; then
        # Tell tmux to pass the escape sequences through
        # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}

# includes
source $HOME/dots/zsh/aliases
source $HOME/dots/zsh/path

pallet

# vi mode
bindkey -v
bindkey "^?" backward-delete-char
zle -N zle-line-init
zle -N zle-keymap-select

# no esc lag
export KEYTIMEOUT=1

function zle-line-init zle-keymap-select {
	if [ $KEYMAP = "vicmd" ]; then
		echo -ne '\033[2 q'
	else
		echo -ne '\033[6 q'
	fi
}

# autocomplete
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'
setopt auto_cd
setopt no_case_glob

# history
setopt inc_append_history
setopt share_history
SAVEHIST=100
HISTFILE=~/.zsh_history

# misc
setopt KSH_ARRAYS

# syntax highlighting
#source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

precmd() {
	printf "%b" "\033]2;${PWD//\/home\/xenone/~}\007"
}

TERMINAL="xfce4-terminal"

set bell-style none
