# prompt
PS1='%B%F{10}%~%b ^_^
$%F{reset} '

# includes
source $HOME/dots/zsh/aliases
source $HOME/dots/zsh/path

# vi mode
bindkey -v
bindkey "^?" backward-delete-char
zle -N zle-line-init
zle -N zle-keymap-select

# no esc lag
export KEYTIMEOUT=1

function zle-line-init zle-keymap-select {
	if [ $KEYMAP = "vicmd" ]; then
		echo -ne '\033[2 q'
	else
		echo -ne '\033[6 q'
	fi
}

# autocomplete
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'
setopt auto_cd
setopt no_case_glob

# history
setopt inc_append_history
setopt share_history
SAVEHIST=100
HISTFILE=~/.zsh_history

# misc
setopt KSH_ARRAYS

# syntax highlighting
#source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
