# prompt
#PS1='%B%F{10}%~%b :(
PS1='%B%F{10}%~%b 🌱
$%F{reset} '

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GO111MODULE=on
DISABLE_AUTO_TITLE=true

# includes
source $HOME/dots/zsh/aliases
source $HOME/dots/zsh/path

pallet

# vi mode
bindkey -v
bindkey "^?" backward-delete-char
zle -N zle-line-init
zle -N zle-keymap-select

# no esc lag
export KEYTIMEOUT=1

function zle-line-init zle-keymap-select {
	if [ $KEYMAP = "vicmd" ]; then
		echo -ne '\033[2 q'
	else
		echo -ne '\033[6 q'
	fi
}

# autocomplete
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'
setopt auto_cd
setopt no_case_glob

# history
setopt inc_append_history
setopt share_history
SAVEHIST=100
HISTFILE=~/.zsh_history

# misc
setopt KSH_ARRAYS

# syntax highlighting
#source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

precmd() {
	printf "%b" "\033]2;${PWD//\/home\/xenone/~}\007"
}

TERMINAL="xfce4-terminal"

set bell-style none
